In [1]:
import pandas as pd
import numpy as np
from pandas import DataFrame
import math

In [26]:
"""Data Preprocess"""

train = pd.read_csv("train.csv", encoding = 'MS950');
# 抓取 每日PM2.5
pm=train[train["測項"]=="PM2.5"].copy()
pm.drop(['日期','測站','測項'],axis=1,inplace=True)

x=[]# x,y為list
y=[]


for i in range(15):
    temx=pm.iloc[:,i:i+9] #temx: keep i~i+8 o'clock
    temx.columns=np.array(range(9))
    temy=pm.iloc[:,i+9] #temy: keep i+9 o'clock
    temy.columns=np.array(range(1))
    x.append(temx) # x = [[eveday 0-8], ..., [eveday 14-22]]
    y.append(temy) # y = [[eveday 9], ..., [eveday 23]]

x=pd.concat(x) # merge x to a dataframe
y=pd.concat(y) # merge y to a series
x=np.array(x,float) # convert to a numpy array
y=np.array(y,float)
np.save("x.npy",x)
np.save("y.npy",y)

In [27]:
x=np.load("x.npy")
y=np.load("y.npy")

# add a bias series with contents = 1 to x
x = np.concatenate((np.ones((x.shape[0],1)),x), axis=1)
# initial
w = np.zeros(len(x[0]))
l_rate = 10
repeat = 10000

# training


[[ 1. 26. 39. ... 25. 20. 19.]
 [ 1. 21. 23. ... 13. 13. 11.]
 [ 1. 19. 25. ... 15.  8.  4.]
 ...
 [ 1. 31. 31. ... 39. 36. 24.]
 [ 1. 21. 21. ... 11.  0.  7.]
 [ 1.  1.  7. ... 28. 17. 24.]]
